[build]
builder = "RAILPACK"
buildCommand = "cd packages/games-convex-backend && npx convex deploy && cd ../../ && pnpm build:poker-planner"

[deploy]
startCommand = "pnpm start:poker-planner"
restartPolicyType = "never"